### ISSUE TITLE
Name of districts

### ISSUE THREAD

**Issue by chincholikarsalil** [bhattbhavesh91/cowin-vaccination-slot-availability#15]
Please refer to the image below.
- We can see that there are two districts of the same name (but in different states)
- It will be convenient if the state's name is added after the district's name

![Screenshot 2021-05-05 235900_LI](https://user-images.githubusercontent.com/31334826/117192734-b206fc00-adff-11eb-9c4c-3c18fb99de05.jpg)

**Comment by bhattbhavesh91** [comment]
Govt closed the API, very little that I can do right now!
