### ISSUE TITLE
Update readme.md

### ISSUE THREAD

**Issue by gajendrasthakur** [bhattbhavesh91/cowin-vaccination-slot-availability#18]
Please **Update readme.md** for _**Beginners**_ so that they also can use this amazing piece you guys have prepared for us. Actually what happens is no one can directly use this master piece as a beginner. So what I wanna convey is Please add some * 1. , * 2. Points like this so that people can understand how to implement and take benefit.

**Comment by Sevansu** [comment]
> Please **Update readme.md** for _**Beginners**_ so that they also can use this amazing piece you guys have prepared for us. Actually what happens is no one can directly use this master piece as a beginner. So what I wanna convey is Please add some * 1. , * 2. Points like this so that people can understand how to implement and take benefit.

1. clone repository locally
2. $ `cd cowin-vaccination-slot-availability-main/`
3. $ `pip3 install -r requirements.txt` 
4. $ `streamlit run app.py`
