### ISSUE TITLE
Can it be automated? 

### ISSUE THREAD

**Issue by sud298** [bhattbhavesh91/cowin-vaccination-slot-availability#22]
Hello Sir;
I have a suggestion, The script is fine. I am running it and it is working flawlessly. Can we automate the process by setting a time interval? Say every 2 minutes or 15 minutes? 

The shortcut is fine. When I press R on the keyboard it is getting executed. Whenever a slot is available a beep notification can be given as well.

**Comment by bhattbhavesh91** [comment]
The initial code has been created. Feel free to improvise on the code :)
