### ISSUE TITLE
Permission Error Screenshot attached

### ISSUE THREAD

**Issue by anisingh62** [bhattbhavesh91/cowin-vaccination-slot-availability#23]
![image](https://user-images.githubusercontent.com/82613527/117573857-e0ceec00-b0f7-11eb-8c31-6e9e7a45824d.png)

Could you please help me in solving this. 
I can give you whatever you want in terms of logs or anything

**Comment by bhattbhavesh91** [comment]
https://stackoverflow.com/questions/65980952/python-could-not-install-packages-due-to-an-oserror-errno-2-no-such-file-or
