### ISSUE TITLE
API not working in program

### ISSUE THREAD

**Issue by pardeep3december** [bhattbhavesh91/cowin-vaccination-slot-availability#24]
Hi,
I am using following code 
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
import requests
import datetime
import json
import pandas as pd

for state_code in range(1,40):
    print("State code: ", state_code)
    response = requests.get("https://cdn-api.co-vin.in/api/v2/admin/location/districts/{}".format(state_code))
    #json_data = json.loads(response.text)
    print (response)
    #for i in json_data["districts"]:
        #print(i["district_id"],'\t', i["district_name"])
    #print("\n")
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

Result is not coming . It is giving <Response [403]> . Whereas same api is working in web browser.

Snapshot attached.
![webbrowser](https://user-images.githubusercontent.com/23492012/117574317-35736680-b0fa-11eb-8e3b-442dd7ade422.png)
![coolab](https://user-images.githubusercontent.com/23492012/117574319-36a49380-b0fa-11eb-96c6-28be7677ee8f.png)

**Comment by bhattbhavesh91** [comment]
Doesn't work on Google Colab! Due to IP issues! Please read the readme file carefully!

**Comment by pardeep3december** [comment]
HI,
Thanks for the update.

Just tried same code on my my laptop.
But result is same.

![Prog_windows](https://user-images.githubusercontent.com/23492012/117575758-de24c480-b100-11eb-9ebf-ebadcbdd7894.png)

**Comment by bhattbhavesh91** [comment]
disconnect the VPN! it only works with Indian IP addresses!

**Comment by bhattbhavesh91** [comment]
and you need to add headers! please go through the app.py file!

**Comment by pardeep3december** [comment]
Thanks @bhattbhavesh91 
I will try and update correspondingly

**Comment by pardeep3december** [comment]
Thanks  @bhattbhavesh91  it's working
