### ISSUE TITLE
Still getting the same error after applying your fix

### ISSUE THREAD

**Issue by anisingh62** [bhattbhavesh91/cowin-vaccination-slot-availability#25]
![image](https://user-images.githubusercontent.com/82613527/117577247-a91b7080-b106-11eb-9efc-dc4fb69546d8.png)
![2021-05-09 (1)](https://user-images.githubusercontent.com/82613527/117577257-b3d60580-b106-11eb-90e0-08fcaac76b5c.png)

**Comment by anisingh62** [comment]
And how can I text you normally so that again and again I dont have to raise an issue as I am new over here

**Comment by bhattbhavesh91** [comment]
Sadly, I haven't ever faced this issue so I won't be able to help you with this. Try searching on Google, Stackoverflow or Youtube for solutions!
