### ISSUE TITLE
Improvement Suggestion for your web app

### ISSUE THREAD

**Issue by Protbhai** [bhattbhavesh91/cowin-vaccination-slot-availability#6]
Your webapp cowin-vaccination-appointment.herokuapp.com is very helpful and you have already provided the code but I am not a programmer, I would suggest you to add some filters like. Minimum age, Availability and date etc. since you already have the data and code ready. the filters shouldn't be a big deal for you to add. 

Thank you

**Comment by bhattbhavesh91** [comment]
Done @Protbhai

**Comment by Protbhai** [comment]
Thank you for the quick update. I really appreciate it. 
Although if you add the Availability option as a checkbox so that we can filter out the centers with 0 available slots, it would be great. 
I am really sorry if I sound very demanding for these feature updates but having this last feature will be very helpful for the users.
